<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sandbox.App\Sandbox.App.csproj" />
  </ItemGroup>
</Project>
